import Head from 'next/head'
import Image from 'next/image'
import { Box, Text, ButtonGroup, Button, } from "@chakra-ui/react"
//components
import Header from "../src/Components/Header"
import LandingPage from "../src/Components/LandingPage"
import Authentication from "../src/Components/Authentication"




export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box w="100%" p="6" px="12">
        <Header />
        <LandingPage />
        <Authentication />
      </Box >
    </>
  )
}
